version: v1.0

fail_fast: true

plan: standard-2

commands:
  - checkout
  - neetoci-version ruby 3.3.5
  - neetoci-version node 22.13
  - neetoci-service start postgres 13
  - neetoci-service start redis 7.0.5

triggers:
  - event: branch
    branch_name: main
  - event: pull_request
